name: Run Kiwi UI Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'tests/ui_tests/test_basic_heroku.py'
      - 'tests/ui_tests/test_academy_bugs.py'
  pull_request:
    branches: [main]

jobs:
  kiwi-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        sudo apt-get update && sudo apt-get install -y xvfb

    - name: Run Kiwi UI tests
      run: |
        source venv/bin/activate
        export PLAYWRIGHT_HEADLESS=false
        xvfb-run -s "-screen 0 1920x1080x24" python3 -m pytest -m basic_search --html=ui_report.html

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-report-kiwi
        path: ui_report.html

  docker-kiwi-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pytest_framework_test .

      - name: Run tests headless (default)
        run: docker run --rm pytest_framework_test