name: Run UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  heroku-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run heroku UI tests
      run: |
        source venv/bin/activate
        export PLAYWRIGHT_HEADLESS=false
        python3 -m pytest -m heroku --html=ui_report.html

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-report-heroku
        path: ui_report.html

  parabank-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Parabank API tests
      run: |
        source venv/bin/activate
        export PLAYWRIGHT_HEADLESS=false
        python3 -m pytest -m parabank --html=ui_report.html

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-report-parabank
        path: ui_report.html
